
platform :ios, '9.0'

target 'lab2' do

pod 'SDWebImage'

pod 'ILMovieDB'

pod 'AFNetworking'

pod 'LHTMDbClient'

pod 'JSONModel'

pod 'EDStarRating'

pod 'RateView'
pod 'CBZSplashView'

pod 'DLStarRating'

end
